language: node_js
node_js:
- '6'
cache:
  directories:
  - node_modules
script:
- npm run build
after_success:
- if ( [ "$TRAVIS_BRANCH" == "master" ] || [ ! -z "$TRAVIS_TAG" ] ) && [ "$TRAVIS_REPO_SLUG"
  == "dhis2/event-capture-app" ]  &&  [ "$TRAVIS_PULL_REQUEST" == "false" ] ; then
  mvn clean deploy --settings deploy/settings.xml && exit 0; fi
env:
  global:
  - secure: Gh/YZJENjaLTUqu/K9Tj1bfenMhzHJjReSWX9sM01a5voUnxmWyfXvxQK791CCIackcYJvYgZfjee6Yf9uN/nUyRQy1i2/8g7y91Tt3e4D7IyeigTAP6b96cDr05ZJFSXCQ7laz1hdkj14bPiv/uVDXP+eUBy31bPhUunc7Q1896wEK8gsGTlR7qlTZNkFG1u1ZPoxa73A4JComczZGlStXnrJQ6FIZP/QbY3GgSjWNUlO+UnSUHwvdMV9tUrwAoKjBcmVxU6TCS5PM61nivkIMw557tyTbSO7IIcx7D7kbYZskehU26cgS0/HSe1hP7upzSFmq2sVLjxvN47FZ+Ms7XH4IkdqZdQtyp2v78juLSrEthkESuiaaAVdYWZWOkPjlZkF3fUTlTh202PZdWr3hlJBOhLw6pMhdnRZe1x6uuaLoC1oOTMCLFIPQw4fSuZokFiSCOWbNe22kOey9LksdMt/bKn/qerJlek35CeKdD4SVC0XarlJ4qHSgLZYVmbSW8PKRFndv67ot5uuuuqS4U5w0oXHbRRRiwpNctZSjhT7P0UbbvWUGr7mMQR6G2r+Zs97kx/G4C3WqdonxWRLRmXPBBVhUi6U0Os89MF6bzSkkQGIHAwasnmQoJ5pwsfOBchuEo9aEVChLwnHIEY5K6aP3rtyDPQqn2SjlyF4c=
  - secure: KYceMIOWh29U/g5aVgmx6Ei4nPegBdMS/3YeNwrqPGWW1KWqlMFTJIbeTFZt3CWKlh0cWBTWddMgcQ9Te65RBh6sUnipE0IqYSyNu/jsgYfOLkMYFN0QWHSHf5M5Tl28z6uYVLENumD9sgu0avKMxMcT/ROvuUPxXGWe7cI+t/Iqin6KGNU5dLCK6T+O0Q9wWLK4qtquw01L+xxHdtBLi1OmFxJDfZeegd88j/URvp4BrpNHQIRFC5vxiYrwzbtsP2XAymWAtn2j5BBDsRjdDkdK+3uea6RVaOb8/zCldVQTWDPeBw3BalBRLyIp7dUtAZ4cf6o0BLk6M4+auKWvBKdIv+fCYuvPbfYzXEnQFTR6pck/lSkiD+HHLTIuhIAVMFkn8OmTujM/s/e8axmyoZOOj4y2Rjw0qFMGNHld9docFXFzPgrID3RFhT1qF2mF42H711jzf2VWF/ylXcVJ/2qRoqH2QHWGDUSb9O5mxDW3ZGZtiUbaGM1hSdAh3F1ml+XkaRaplkn45KgfM9RPRn8dlWECL1p3SLGtY6glRZjZ4N9DVa1mNyN9QZ38TM3n5bCpWFI0b3GMeTvgQUwI8ZE/du/tpwBwu176Apn4Sjud5lcZGiA1CNvULvY6KecTZzSljoiRNjqRAf11D41TkIsCWWcDXaqkIPbCjq9GA6U=
