language: node_js
node_js:
- '6'
cache:
  directories:
  - node_modules
script:
- npm run build
after_success:
- if ( [ "$TRAVIS_BRANCH" == "master" ] || [ ! -z "$TRAVIS_TAG" ] ) && [ "$TRAVIS_REPO_SLUG"
  == "dhis2/event-capture-app" ]  &&  [ "$TRAVIS_PULL_REQUEST" == "false" ] ; then
  mvn clean deploy --settings deploy/settings.xml && exit 0 fi
env:
  global:
  - secure: alfqv1tn0OX/hq7uzL9r+1+AENYoHpSZOFGU8TCbLX5GRohaTs/4lDS/2QSgo6Dwj3E9fXZbf0MHLtgm10LPSIFdSuGyZ+A+Pr70r3Q0OfXN7+OlzE0q/8PPfcTstmaTRdfC5Z/3cqGpE0lbj/OIs0lVdYxXhqgCmba6KCf306noYNSqQESs3utEt2clSUANJS6ehND6VtNLOQk77Itjr8G8bd864aTOoL8pwsmVMkY0Y4742RxjnYl8iYBxX6u2oy1Lepal0IMaMqD2H6oFYPaahsy0XFUxKVJQLIMvrhV2/vjeHbXqhT1WOSEMQT8G8G25i9PVDBxpX7cRTVUoFt+JcO/M41u6pi/s0Nyz4kokhms5NVnRVV1GvEum1HqaIrgUvjRgwb8b6p4n4k+YL3KrF65yejKEUTWsZBXUmaaLsBOb+F7Nm9cVW5iiEToEvrkwu7Rpen+fQh/PEbfiURxURQPkpUUASfD3Ht6JXtF3fc0unpEnL1BnpbfYq55LwytvWHplcMx13BZ/5UfEuIJvgm/HlOymOQOnZYQpnHtug+fd5+arrBL0CJFPAAt+mxpHWqUCB6RRgK9bc5EioDTL+Os+OTQnsQJgScs0318daxCERVuyCUQ+GD1YtpspkbqmX7ouCerWBgWxwyHxIYXrN6VKAelIQPLlHGxL4UI=
  - secure: bfd8DwprV+X4379OIKPjJOg+WS4BDtCvZUzu7fUKqZUY8dJWIYXWN1Fibty97YZvtQgJbqqgIgIlLNbsWoD9x9rhjt0RY14bzLMPefeBtoS2DHejiO7MQovRH84qV11R92RMLIDR+qWhiDaSM9GKDlXbOxhVMcPtV6IwRxgbLOtTbCaYW9x3qN/y6NiV1ouXX2hnfi0rkUadRyVhnp/kMTvrZ+NB/FzXR34b4Yi+KGyWMqjWZ7/pnYibymc9tfOj9AKXfkrY/0fSqORRPvfOYcgDkTWoutiElWa95J9pmhr7K+W3m16oh/1z4GbXpEPSm6bEAOuoxN8OFe6ebIEszIIOIWZO6WV7svmnDPO6ua3RDHK7UqhE1dRsjLg5Yhj9aknjEmwbcBNa5PIhKpnHpkhtQp5kti0MOQzHm7dfZLBb6yvtC87iCMQEXJCz2AJLMY60uhp9Sxpq0efVmnXwqQ27b+okUlH34DeVLK4s+s+ZtmZ5IzFru2e4L3yf0fqrjvmNkHrjI9Rrz5+2VASXeuU/vgf2O296L1Ctr+cJBkyqGzJ37jUi8PQPxk9HZl1nBmtekLSGS1hK/zO0ChMzmZ/7mWe8VXXdk+gYSmT5xBXY4D7qa5cDsuShlJYmMeLUGm1JWc6LDlVRjMIIXhJY/Oll6YmLGzJwc/ZUg+sSC+U=
