language: node_js
node_js:
- '6'
cache:
  directories:
  - node_modules
script:
- npm run build
after_success:
- if ( [ "$TRAVIS_BRANCH" == "master" ] || [ ! -z "$TRAVIS_TAG" ] ) && [ "$TRAVIS_REPO_SLUG" == "dhis2/event-capture-app" ]  &&  [ "$TRAVIS_PULL_REQUEST" == "false" ] ; then
    mvn clean deploy --settings deploy/settings.xml && exit 0; 
  fi
env:
  global:
  - secure: rnJyR4adIWAm0rgjDEu3lV21m79K4NUUbuyn3kHnfkj/+cnyKVc3lpAEgaGHFoYE3a7njeSxQyjpGNwJZwPi43sPikYrBuAP3dvvfMEKzpVdXnrR5F32C1DNDCkYgauSLi2kSNcLftgtULTiT1+/wrZK61ZABaOw4DhYI8baLtHuK8yM3I1x4VhzJvAvIOtVdSydEUWIphgqM9LcmAhwScFLUo87v0qGyYsqoo/TdN7Qk/BGLGTa3xCOB5g6te4HYTF8ZJU760/NLc1v8DLrH+aKj8LRau+CG67DqT8AhXd+PqPX9AeTlNqtwPU78scgypbriFTd1l83XlkyXWnPIHNEIvc1ASnQRCkxLBSN5h56Hkpawuv5p30+8db2i7u/xI/dvWEqwIEILjkrIP1/Nbe1f8iqhAqqnDDpnDosjeBNlYs4xds9c4tfSTnWQtXT/7yLMZ7EghRw8Wov58EK4B8+4vk0ZgvMxF6LMS2T7Npe66gKaZ1R2BQ6j5/0m68LPza7O0JN018+jZ5O5AsyPwg1yljORl9NehZ1lSgPnK/s3AihQLxdeX580W5ON8KGjeRmW7h0KjFkRWxr7TY3JilI4gVxci0YbI6k0OYpdqwruKOb2gHc5fYs/2BNjtxlBzo/7XVGWsUTskuwTea8cR4fQurMf74ads/5HEWO93U=
  - secure: DCXfElhuhoqjIzIlskEsfoEApWItMfugNY8LQNVQhWB98DPhZleRKaHGA6MKBpo1iX3lJa/N80mvBKPjnyirHlQRFhTJmdd+ONn/YU5VvfmLVO1Bgdx9FoxpyttPEQlJvDYyl3C+Hca+MwW9699SDB4dkLvbvdzc2NnH/jbZd2tLGIPceP+JJboOZZQc7AbjDpC+chQwz23uaa7cCKlmGrdjOpul8GXYaGyL26IS8f6S350kq95K9GhJ4BTt2936a3UWq4s/v748RMYSS1sx8U36ptdzrGkEiBpPBHon24d7Hnt4wvz13vKROvfV3RADMCP9mE+j28Aau97UXsF8onl5X15zjIO+A0yputxRl2wZURHxmvHNBrSRnWxW+He+xe8bptWLmcVy9H8XY1G43ZY/jBs1fj1HH7AuZEJeSfgzQOj924DPooCw41322uJMxJKojsrOR8jPMUu2D+kNob/y2ESNq3BGL2x6Hp6bEqLjdF7d8c1yKVthLoq5GefubVvqL7oiUXG+zLIgP4x/xjHzFh4F2BJrPxYZn9Q/PjjGrAIpi/z/w8uEe0xKEvopm3sBYk9RC4SIih0rh7lr0QgYkDtVqKoUWPV7GhmtjDKcd7WX5Mvob7mweZjNkzsQoh1tjdmWNMwE6od62beyjNCAuXgBQ/UlHftx0cPRZ9E=
notifications:
  slack:
    secure: WReEyMu+bgmypE1CZ0eQDQ5bzAOT9znnrFD1925s23yOStjsWH/i8HOj6LUH8orJtzPwSGMXBkBIZNfg4n0kUzUKc47bJRKzFPPrrpbxc1Gx9O3TKjg3sY/pb03rbayTXJ9gxFwvnW7qd66NcuAy3UIBlei38s6HL+OrAuBPrzW190A1f7Fn3aNDN8qoG4zIWLW4Z4KZ5EA3iPHDCVl9t2V1eGveHN3eaGfASMifdmUTbXna7/KuOUMEPpw3mL6mptwk9JYvl2Zyg0Eg//gW9A5zNWmae3d0jz+fiX5utyyaH3i3hFLeNclL6VPZSZrR03S6kZSAe903N32hq+ox+rsMCbtqntHdTQT/q6sTbaG0Rjp/v9wJysgQV/2+LBrOMVN9ECBB7ErIITI6FXVFSigCJ4Fft9gEiqaekrCuob5bSr91XTSny2bXtPCUJl3+loIo4aAonANmEdN7K34OQmB9Io7WWkNmKiZGFFyItUlCy9F5zSCxrfZJX1QicfnP9hJyJXS7BwhuWc6WpHHoZ6mHFWXD07XyhKgIf6msGqyARHFDXe7P9759V+d1GZoeUKhllUhJd8YouVIX2ZxDzn9XL2a6/pfELr2aVnOKgMNEFPLvLv6u5RDZUfIsCaFx6PoQINauvYwvx7zAfvvqE3QGJEyUivqDJQZj1aOuAkM=
    on_success: change
    on_faiure: always
