language: node_js
node_js:
- '6'
cache:
  directories:
  - node_modules
script:
- npm run build
after_success:
- if ( [ "$TRAVIS_BRANCH" == "master" ] || [ ! -z "$TRAVIS_TAG" ] ) && [ "$TRAVIS_REPO_SLUG"
  == "dhis2/event-capture-app" ]  &&  [ "$TRAVIS_PULL_REQUEST" == "false" ] ; then
  mvn clean deploy --settings deploy/settings.xml && exit 0 fi
env:
  global:
  - secure: rcNAetPoXFtRhgsv0WnPX+R7WqqjJXYxzmK8Kvr9bKbqI1BbkCxGL4Ft+U4etVyPCnTaFFJEZ2ZD4BemtCBOyEyXAXGta40vwwByDDwrR6P07g/wMqIeNhT0Dtq7JSV1WGW+HLYrzG/JK0TbxIBhz+5QEciVk4sQmEVy2DXlSdkJBVSeglU1djdb37cPmktkiXqI5uMT/+QdcAIguGWMV8rt5VAx8Bqt21yFxj+KRMiCfkPhoNvQN9APri3Vmu8ujTxGYlieHhaAndPECe2X7hDkwSJ7Ji14xvx4gniSATeAqJemEDQdn22BtcAT9BW5cUxYq52QvRwRTMJ1qoHGEidh6oY6FKzBcybXTCAUu30J+t16OugO8RW2KnUzVPjzigrlQPIDZBJS0bWzzJ7JyhqF5pdPJGoccqZ9qLebajn+bHqKwcGCPUyqj7uNKEqWA8rPkom7Blk/Ib1RasbMDZx/xnH7pm7CYMtneew/1w4SWKUhNnqN/uqKgbmmNmRf07tOgc2M3AnEnedfNABm025LoYNwCLuYg/16+9mUtS1EMwT6GKxVYf87YPbB+ItH2tM/oMWEmVZNrUiyN6rwiJBwSXQcQkTbjePhKpEKVgWbxZbASfJadSDxvHIe6ZJsX6Ds04Pa1KuIuB1Repro0HjjW5MB1OpcwHoWiRq2/ks=
  - secure: jVCt9L1AeRvKO1QgeH9WQjXMq6dd+c3FswmZr1qQasJXnO/1xnHU5zkewGmYrf2xRjy4QCZfcThGEgFX/x2KWwyiWNZdxUYvkHeRsrS5ziEZr0RzcMFg7Nhnf10GN23Prr8YE8yZl9aLgt0AtA0O/gCPE1b25YG8ln0VlLMRUaZKFM4D+Q+pqea+1q41ztbCQneoV1GgIWeeJKUjAgrumCezhNH0iv1I5vYJQvqHHfOF9J2AQ8yY/z25dLajPv7t7wJkZIHG/NxmjmZHFbk+RHuvNUw2sHSOtr1KtJu1RpIXUzeKp2KxKzBu4TgC6EuKxctbH5YfKMS6LUqp1K/KsJkz/pJvbDongcf1BzteYAG89BlyHP1J9JmGGv2FVzXmeq/fdwyB4heINbSKd9BuMbv6rTAV4k4oy9wVG4kJtqZ1JY/UfVIiqBddY5T/rnkNgp7P0oFz2g1MiTVsP81hpTcZ/MMUsdJme/aU3ixSrLlL6TnF8pDjYqgoitK1B5cAEQrm7Uxi8Crx4s8FC8gyO+EaF5DhWDdkpF4hGAzSNm0n7xcdVOP6GCqnzZLq47FhiPgFfXdpXBOoO7Lb1Kzox0ZGmrf7uvqfcFJi9CnH+RDuIxK5+2Q62I+yN6PruOe8gOdr3jY8WH8D+Pm52nE15WpCI2Vf0bpIetNc6h+53KU=
